package com.phicomm.doctor.dataaccess.domain;

public class Department {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.department_name
	 * @mbg.generated
	 */
	private String departmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.parent_department_id
	 * @mbg.generated
	 */
	private Integer parentDepartmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.parent_department_name
	 * @mbg.generated
	 */
	private String parentDepartmentName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.id
	 * @return  the value of department.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.id
	 * @param id  the value for department.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.department_name
	 * @return  the value of department.department_name
	 * @mbg.generated
	 */
	public String getDepartmentName() {
		return departmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.department_name
	 * @param departmentName  the value for department.department_name
	 * @mbg.generated
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName == null ? null : departmentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.parent_department_id
	 * @return  the value of department.parent_department_id
	 * @mbg.generated
	 */
	public Integer getParentDepartmentId() {
		return parentDepartmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.parent_department_id
	 * @param parentDepartmentId  the value for department.parent_department_id
	 * @mbg.generated
	 */
	public void setParentDepartmentId(Integer parentDepartmentId) {
		this.parentDepartmentId = parentDepartmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.parent_department_name
	 * @return  the value of department.parent_department_name
	 * @mbg.generated
	 */
	public String getParentDepartmentName() {
		return parentDepartmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.parent_department_name
	 * @param parentDepartmentName  the value for department.parent_department_name
	 * @mbg.generated
	 */
	public void setParentDepartmentName(String parentDepartmentName) {
		this.parentDepartmentName = parentDepartmentName == null ? null : parentDepartmentName.trim();
	}
}