package com.phicomm.doctor.dataaccess.domain;

import java.util.Date;

import com.alibaba.fastjson.JSONObject;

public class Doctor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.openid
	 * @mbg.generated
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.head_img_url
	 * @mbg.generated
	 */
	private String headImgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.sex
	 * @mbg.generated
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.education
	 * @mbg.generated
	 */
	private Integer education;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.work_time
	 * @mbg.generated
	 */
	private Integer workTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.birthday
	 * @mbg.generated
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.province
	 * @mbg.generated
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.city
	 * @mbg.generated
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.phone
	 * @mbg.generated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.department_id
	 * @mbg.generated
	 */
	private Integer departmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.department_name
	 * @mbg.generated
	 */
	private String departmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.title
	 * @mbg.generated
	 */
	private Integer title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.profession_card_url
	 * @mbg.generated
	 */
	private String professionCardUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.qualification_card_url
	 * @mbg.generated
	 */
	private String qualificationCardUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.practice_card_url
	 * @mbg.generated
	 */
	private String practiceCardUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.audit_status
	 * @mbg.generated
	 */
	private Integer auditStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.complete_status
	 * @mbg.generated
	 */
	private Integer completeStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.call
	 * @mbg.generated
	 */
	private String call;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.work_experience
	 * @mbg.generated
	 */
	private String workExperience;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.education_experience
	 * @mbg.generated
	 */
	private String educationExperience;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.works
	 * @mbg.generated
	 */
	private String works;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.good_field
	 * @mbg.generated
	 */
	private String goodField;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column doctor.profile
	 * @mbg.generated
	 */
	private String profile;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.id
	 * @return  the value of doctor.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.id
	 * @param id  the value for doctor.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.openid
	 * @return  the value of doctor.openid
	 * @mbg.generated
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.openid
	 * @param openid  the value for doctor.openid
	 * @mbg.generated
	 */
	public void setOpenid(String openid) {
		this.openid = openid == null ? null : openid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.head_img_url
	 * @return  the value of doctor.head_img_url
	 * @mbg.generated
	 */
	public String getHeadImgUrl() {
		return headImgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.head_img_url
	 * @param headImgUrl  the value for doctor.head_img_url
	 * @mbg.generated
	 */
	public void setHeadImgUrl(String headImgUrl) {
		this.headImgUrl = headImgUrl == null ? null : headImgUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.name
	 * @return  the value of doctor.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.name
	 * @param name  the value for doctor.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.sex
	 * @return  the value of doctor.sex
	 * @mbg.generated
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.sex
	 * @param sex  the value for doctor.sex
	 * @mbg.generated
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.education
	 * @return  the value of doctor.education
	 * @mbg.generated
	 */
	public Integer getEducation() {
		return education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.education
	 * @param education  the value for doctor.education
	 * @mbg.generated
	 */
	public void setEducation(Integer education) {
		this.education = education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.work_time
	 * @return  the value of doctor.work_time
	 * @mbg.generated
	 */
	public Integer getWorkTime() {
		return workTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.work_time
	 * @param workTime  the value for doctor.work_time
	 * @mbg.generated
	 */
	public void setWorkTime(Integer workTime) {
		this.workTime = workTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.birthday
	 * @return  the value of doctor.birthday
	 * @mbg.generated
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.birthday
	 * @param birthday  the value for doctor.birthday
	 * @mbg.generated
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.province
	 * @return  the value of doctor.province
	 * @mbg.generated
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.province
	 * @param province  the value for doctor.province
	 * @mbg.generated
	 */
	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.city
	 * @return  the value of doctor.city
	 * @mbg.generated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.city
	 * @param city  the value for doctor.city
	 * @mbg.generated
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.phone
	 * @return  the value of doctor.phone
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.phone
	 * @param phone  the value for doctor.phone
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.department_id
	 * @return  the value of doctor.department_id
	 * @mbg.generated
	 */
	public Integer getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.department_id
	 * @param departmentId  the value for doctor.department_id
	 * @mbg.generated
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.department_name
	 * @return  the value of doctor.department_name
	 * @mbg.generated
	 */
	public String getDepartmentName() {
		return departmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.department_name
	 * @param departmentName  the value for doctor.department_name
	 * @mbg.generated
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName == null ? null : departmentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.title
	 * @return  the value of doctor.title
	 * @mbg.generated
	 */
	public Integer getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.title
	 * @param title  the value for doctor.title
	 * @mbg.generated
	 */
	public void setTitle(Integer title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.profession_card_url
	 * @return  the value of doctor.profession_card_url
	 * @mbg.generated
	 */
	public String getProfessionCardUrl() {
		return professionCardUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.profession_card_url
	 * @param professionCardUrl  the value for doctor.profession_card_url
	 * @mbg.generated
	 */
	public void setProfessionCardUrl(String professionCardUrl) {
		this.professionCardUrl = professionCardUrl == null ? null : professionCardUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.qualification_card_url
	 * @return  the value of doctor.qualification_card_url
	 * @mbg.generated
	 */
	public String getQualificationCardUrl() {
		return qualificationCardUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.qualification_card_url
	 * @param qualificationCardUrl  the value for doctor.qualification_card_url
	 * @mbg.generated
	 */
	public void setQualificationCardUrl(String qualificationCardUrl) {
		this.qualificationCardUrl = qualificationCardUrl == null ? null : qualificationCardUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.practice_card_url
	 * @return  the value of doctor.practice_card_url
	 * @mbg.generated
	 */
	public String getPracticeCardUrl() {
		return practiceCardUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.practice_card_url
	 * @param practiceCardUrl  the value for doctor.practice_card_url
	 * @mbg.generated
	 */
	public void setPracticeCardUrl(String practiceCardUrl) {
		this.practiceCardUrl = practiceCardUrl == null ? null : practiceCardUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.audit_status
	 * @return  the value of doctor.audit_status
	 * @mbg.generated
	 */
	public Integer getAuditStatus() {
		return auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.audit_status
	 * @param auditStatus  the value for doctor.audit_status
	 * @mbg.generated
	 */
	public void setAuditStatus(Integer auditStatus) {
		this.auditStatus = auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.complete_status
	 * @return  the value of doctor.complete_status
	 * @mbg.generated
	 */
	public Integer getCompleteStatus() {
		return completeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.complete_status
	 * @param completeStatus  the value for doctor.complete_status
	 * @mbg.generated
	 */
	public void setCompleteStatus(Integer completeStatus) {
		this.completeStatus = completeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.create_time
	 * @return  the value of doctor.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.create_time
	 * @param createTime  the value for doctor.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.update_time
	 * @return  the value of doctor.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.update_time
	 * @param updateTime  the value for doctor.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getCall() {
		return call;
	}

	public void setCall(String call) {
		this.call = call;
	}

	public String getWorkExperience() {
		return workExperience;
	}

	public void setWorkExperience(String workExperience) {
		this.workExperience = workExperience;
	}

	public String getEducationExperience() {
		return educationExperience;
	}

	public void setEducationExperience(String educationExperience) {
		this.educationExperience = educationExperience;
	}

	public String getWorks() {
		return works;
	}

	public void setWorks(String works) {
		this.works = works;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.good_field
	 * @return  the value of doctor.good_field
	 * @mbg.generated
	 */
	public String getGoodField() {
		return goodField;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.good_field
	 * @param goodField  the value for doctor.good_field
	 * @mbg.generated
	 */
	public void setGoodField(String goodField) {
		this.goodField = goodField == null ? null : goodField.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column doctor.profile
	 * @return  the value of doctor.profile
	 * @mbg.generated
	 */
	public String getProfile() {
		return profile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column doctor.profile
	 * @param profile  the value for doctor.profile
	 * @mbg.generated
	 */
	public void setProfile(String profile) {
		this.profile = profile == null ? null : profile.trim();
	}
}