package com.phicomm.doctor.dataaccess.domain;

import java.util.Date;

public class Hospital {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.openid
	 * @mbg.generated
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.logo_img_url
	 * @mbg.generated
	 */
	private String logoImgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.address
	 * @mbg.generated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.province
	 * @mbg.generated
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.city
	 * @mbg.generated
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.phone
	 * @mbg.generated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.scale
	 * @mbg.generated
	 */
	private Integer scale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.tag
	 * @mbg.generated
	 */
	private String tag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.business_licence_url
	 * @mbg.generated
	 */
	private String businessLicenceUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.audit_status
	 * @mbg.generated
	 */
	private Integer auditStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.complete_status
	 * @mbg.generated
	 */
	private Integer completeStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.good_field
	 * @mbg.generated
	 */
	private String goodField;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.profile
	 * @mbg.generated
	 */
	private String profile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.image_url
	 * @mbg.generated
	 */
	private String imageUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital.works
	 * @mbg.generated
	 */
	private String works;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.id
	 * @return  the value of hospital.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.id
	 * @param id  the value for hospital.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.openid
	 * @return  the value of hospital.openid
	 * @mbg.generated
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.openid
	 * @param openid  the value for hospital.openid
	 * @mbg.generated
	 */
	public void setOpenid(String openid) {
		this.openid = openid == null ? null : openid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.name
	 * @return  the value of hospital.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.name
	 * @param name  the value for hospital.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.logo_img_url
	 * @return  the value of hospital.logo_img_url
	 * @mbg.generated
	 */
	public String getLogoImgUrl() {
		return logoImgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.logo_img_url
	 * @param logoImgUrl  the value for hospital.logo_img_url
	 * @mbg.generated
	 */
	public void setLogoImgUrl(String logoImgUrl) {
		this.logoImgUrl = logoImgUrl == null ? null : logoImgUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.address
	 * @return  the value of hospital.address
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.address
	 * @param address  the value for hospital.address
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.province
	 * @return  the value of hospital.province
	 * @mbg.generated
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.province
	 * @param province  the value for hospital.province
	 * @mbg.generated
	 */
	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.city
	 * @return  the value of hospital.city
	 * @mbg.generated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.city
	 * @param city  the value for hospital.city
	 * @mbg.generated
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.phone
	 * @return  the value of hospital.phone
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.phone
	 * @param phone  the value for hospital.phone
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.scale
	 * @return  the value of hospital.scale
	 * @mbg.generated
	 */
	public Integer getScale() {
		return scale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.scale
	 * @param scale  the value for hospital.scale
	 * @mbg.generated
	 */
	public void setScale(Integer scale) {
		this.scale = scale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.tag
	 * @return  the value of hospital.tag
	 * @mbg.generated
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.tag
	 * @param tag  the value for hospital.tag
	 * @mbg.generated
	 */
	public void setTag(String tag) {
		this.tag = tag == null ? null : tag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.business_licence_url
	 * @return  the value of hospital.business_licence_url
	 * @mbg.generated
	 */
	public String getBusinessLicenceUrl() {
		return businessLicenceUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.business_licence_url
	 * @param businessLicenceUrl  the value for hospital.business_licence_url
	 * @mbg.generated
	 */
	public void setBusinessLicenceUrl(String businessLicenceUrl) {
		this.businessLicenceUrl = businessLicenceUrl == null ? null : businessLicenceUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.audit_status
	 * @return  the value of hospital.audit_status
	 * @mbg.generated
	 */
	public Integer getAuditStatus() {
		return auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.audit_status
	 * @param auditStatus  the value for hospital.audit_status
	 * @mbg.generated
	 */
	public void setAuditStatus(Integer auditStatus) {
		this.auditStatus = auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.complete_status
	 * @return  the value of hospital.complete_status
	 * @mbg.generated
	 */
	public Integer getCompleteStatus() {
		return completeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.complete_status
	 * @param completeStatus  the value for hospital.complete_status
	 * @mbg.generated
	 */
	public void setCompleteStatus(Integer completeStatus) {
		this.completeStatus = completeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.create_time
	 * @return  the value of hospital.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.create_time
	 * @param createTime  the value for hospital.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.update_time
	 * @return  the value of hospital.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.update_time
	 * @param updateTime  the value for hospital.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.good_field
	 * @return  the value of hospital.good_field
	 * @mbg.generated
	 */
	public String getGoodField() {
		return goodField;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.good_field
	 * @param goodField  the value for hospital.good_field
	 * @mbg.generated
	 */
	public void setGoodField(String goodField) {
		this.goodField = goodField == null ? null : goodField.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.profile
	 * @return  the value of hospital.profile
	 * @mbg.generated
	 */
	public String getProfile() {
		return profile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.profile
	 * @param profile  the value for hospital.profile
	 * @mbg.generated
	 */
	public void setProfile(String profile) {
		this.profile = profile == null ? null : profile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.image_url
	 * @return  the value of hospital.image_url
	 * @mbg.generated
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.image_url
	 * @param imageUrl  the value for hospital.image_url
	 * @mbg.generated
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl == null ? null : imageUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital.works
	 * @return  the value of hospital.works
	 * @mbg.generated
	 */
	public String getWorks() {
		return works;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital.works
	 * @param works  the value for hospital.works
	 * @mbg.generated
	 */
	public void setWorks(String works) {
		this.works = works == null ? null : works.trim();
	}
}