package com.phicomm.doctor.dataaccess.domain;

import java.util.Date;

public class HospitalRelease {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.hospital_id
	 * @mbg.generated
	 */
	private Integer hospitalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.department_id
	 * @mbg.generated
	 */
	private Integer departmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.department_name
	 * @mbg.generated
	 */
	private String departmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.title
	 * @mbg.generated
	 */
	private String title;
	
	private Integer doctorTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.education
	 * @mbg.generated
	 */
	private Integer education;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.work_time
	 * @mbg.generated
	 */
	private Integer workTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.money_type
	 * @mbg.generated
	 */
	private Integer moneyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.audit_status
	 * @mbg.generated
	 */
	private Integer auditStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.job_description
	 * @mbg.generated
	 */
	private String jobDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hospital_release.job_require
	 * @mbg.generated
	 */
	private String jobRequire;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.id
	 * @return  the value of hospital_release.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.id
	 * @param id  the value for hospital_release.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.hospital_id
	 * @return  the value of hospital_release.hospital_id
	 * @mbg.generated
	 */
	public Integer getHospitalId() {
		return hospitalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.hospital_id
	 * @param hospitalId  the value for hospital_release.hospital_id
	 * @mbg.generated
	 */
	public void setHospitalId(Integer hospitalId) {
		this.hospitalId = hospitalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.department_id
	 * @return  the value of hospital_release.department_id
	 * @mbg.generated
	 */
	public Integer getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.department_id
	 * @param departmentId  the value for hospital_release.department_id
	 * @mbg.generated
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.department_name
	 * @return  the value of hospital_release.department_name
	 * @mbg.generated
	 */
	public String getDepartmentName() {
		return departmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.department_name
	 * @param departmentName  the value for hospital_release.department_name
	 * @mbg.generated
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName == null ? null : departmentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.education
	 * @return  the value of hospital_release.education
	 * @mbg.generated
	 */
	public Integer getEducation() {
		return education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.education
	 * @param education  the value for hospital_release.education
	 * @mbg.generated
	 */
	public void setEducation(Integer education) {
		this.education = education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.work_time
	 * @return  the value of hospital_release.work_time
	 * @mbg.generated
	 */
	public Integer getWorkTime() {
		return workTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.work_time
	 * @param workTime  the value for hospital_release.work_time
	 * @mbg.generated
	 */
	public void setWorkTime(Integer workTime) {
		this.workTime = workTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.time
	 * @return  the value of hospital_release.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.time
	 * @param time  the value for hospital_release.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.money_type
	 * @return  the value of hospital_release.money_type
	 * @mbg.generated
	 */
	public Integer getMoneyType() {
		return moneyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.money_type
	 * @param moneyType  the value for hospital_release.money_type
	 * @mbg.generated
	 */
	public void setMoneyType(Integer moneyType) {
		this.moneyType = moneyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.audit_status
	 * @return  the value of hospital_release.audit_status
	 * @mbg.generated
	 */
	public Integer getAuditStatus() {
		return auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.audit_status
	 * @param auditStatus  the value for hospital_release.audit_status
	 * @mbg.generated
	 */
	public void setAuditStatus(Integer auditStatus) {
		this.auditStatus = auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.status
	 * @return  the value of hospital_release.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.status
	 * @param status  the value for hospital_release.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.create_time
	 * @return  the value of hospital_release.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.create_time
	 * @param createTime  the value for hospital_release.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.update_time
	 * @return  the value of hospital_release.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.update_time
	 * @param updateTime  the value for hospital_release.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.job_description
	 * @return  the value of hospital_release.job_description
	 * @mbg.generated
	 */
	public String getJobDescription() {
		return jobDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.job_description
	 * @param jobDescription  the value for hospital_release.job_description
	 * @mbg.generated
	 */
	public void setJobDescription(String jobDescription) {
		this.jobDescription = jobDescription == null ? null : jobDescription.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hospital_release.job_require
	 * @return  the value of hospital_release.job_require
	 * @mbg.generated
	 */
	public String getJobRequire() {
		return jobRequire;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hospital_release.job_require
	 * @param jobRequire  the value for hospital_release.job_require
	 * @mbg.generated
	 */
	public void setJobRequire(String jobRequire) {
		this.jobRequire = jobRequire == null ? null : jobRequire.trim();
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getDoctorTitle() {
		return doctorTitle;
	}

	public void setDoctorTitle(Integer doctorTitle) {
		this.doctorTitle = doctorTitle;
	}

}