package com.phicomm.doctor.dataaccess.dao;

import com.phicomm.doctor.dataaccess.domain.DoctorRelese;

public interface DoctorReleseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor_relese
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor_relese
	 * @mbg.generated
	 */
	int insert(DoctorRelese record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor_relese
	 * @mbg.generated
	 */
	int insertSelective(DoctorRelese record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor_relese
	 * @mbg.generated
	 */
	DoctorRelese selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor_relese
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(DoctorRelese record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table doctor_relese
	 * @mbg.generated
	 */
	int updateByPrimaryKey(DoctorRelese record);
}