package com.phicomm.doctor.dataaccess.dao;

import com.phicomm.doctor.dataaccess.domain.HospitalRelease;

public interface HospitalReleaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital_release
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital_release
	 * @mbg.generated
	 */
	int insert(HospitalRelease record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital_release
	 * @mbg.generated
	 */
	int insertSelective(HospitalRelease record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital_release
	 * @mbg.generated
	 */
	HospitalRelease selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital_release
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(HospitalRelease record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital_release
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(HospitalRelease record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital_release
	 * @mbg.generated
	 */
	int updateByPrimaryKey(HospitalRelease record);
}